### ISSUE TITLE
Suggestion to add info on income category

### ISSUE THREAD

**Issue by santoshceft** [jpazvd/wbopendata#2]
Dear Professor,
I would like to thank you for creating this beautiful module, wbopendata, for researchers. This saves a lot of time and energy.

**I was wondering whether the module provides information on income code or income category of countries like it provides information on region.**

I checked it and it seems it does not exist at present. I would really appreciate if you can suggest ways on how to add it...

It would be really great if you can add this information if you are considering updating the module.

Thank you.

**Comment by jpazvd** [comment]
Dear Santosh,
Many thanks for your suggestion.
We will include it in our To-Do List!
Many thanks
JP

**Comment by jpazvd** [comment]
Hell Santosh,
please check the new version of wbopendata by typing in I have added the features you have suggested, and a few more:

net install github, from("https://haghish.github.io/github/")
github install jpazvd/wbopendata, force

Please let me know if you have any problems.
Best regards,
JP

**Comment by santoshceft** [comment]
Dear Sir,
My apologies for the late reply.
I am grateful to you for adding income-category information to the WDI
database.
I just installed now and it is working.


Thank you.
..................
Regards
Santosh K. Dash
Center of Excellence in Fiscal Policy and Taxation (CEFT)
https://sites.google.com/site/santoshdashecon/
https://macrotalks.blogspot.in/

**Comment by jpazvd** [comment]
Great!
