### ISSUE TITLE
No download of country attributes / documentation of match function 

### ISSUE THREAD

**Issue by oliverfiala** [jpazvd/wbopendata#34]
Hi,
I have updated the Stata version just now after reading your [blog post](https://blogs.worldbank.org/opendata/new-release-wbopendata-stata-module?CID=WBW_AL_BlogNotification_EN_EXT). First, let me say congratulation to all those new changes, what a helpful tool.
However, I am not currently not able to download the full list of attributes (region, income level etc.) despite specifying the 'pull' option. For instance `wbopendata, indicator(sp.pop.totl) full long clear` only gives me countrycode, countryname, indicator and sp_pop_totl.

Also would it be possible to share an example on the new match option on GitHub?

Many thanks!
Oliver

**Comment by jpazvd** [comment]
Thanks for your interest.
Please run the update of attributes beforehand by typing :

wbopendata, metadataoffline

**Comment by oliverfiala** [comment]
Thanks, that works well!

**Comment by oliverfiala** [comment]
Hi Joao,
Could you I quickly clarify if the new version requires me to download the metadata in every relevant working directory or is there a way to ensure that this is downloaded once and used across various working directories?
Thanks,
Oliver

**Comment by jpazvd** [comment]
It depends, when and how you ran wbopendata.
You should only need to install it once in the root directly where wbopendata is.

In the stata command line, type:

which wbopendata
cd “<type here that path of wbopendata>” (in general it should be something like: “c:\ado\plus\w\”)
wbopendata, metadataoffline

That that should be it.

Best,

JP

**Comment by oliverfiala** [comment]
Thanks for getting back to quickly, very much appreciated. It still doesn't work completely - if I change to the ado directory and run wbopendata, it does work. Afterwards I can change to other locations and it still works. However, the next time I am starting Stata I have the same issue again and would need to go to to the ado folder first. This might be an issue on my end, but I wonder if you can replicate this as well?
Oliver

**Comment by lcrawfurd** [comment]
I'm having a similar issue with the new update, but when I run 

wbopendata, metadataoffline

I get an error message saying 

varlist not allowed

Thanks again for building this tool, it must have saved me and many other people hours of time.

**Comment by ckrf** [comment]
It doesn't look like exactly the same issue that @lcrawfurd and @oliverfiala were reporting, but with version 16.3, the 'full' option was not affecting which metadata were downloaded. [This pull request](https://github.com/jpazvd/wbopendata/pull/40) addresses that issue.

**Comment by ennoschroeder** [comment]
I run: 
`wbopendata, metadataoffline`
Then:
`wbopendata, indicator(sp.pop.totl) full long clear`
But not all country attributes are downloaded. I want capital, longitude, and latitude, but can't get those variables.
`which wbopendata` returns:
```
C:\Users\username\ado\plus\w\wbopendata.ado
*! v 16.3       8Jul2020               by Joao Pedro Azevedo
```
