### ISSUE TITLE
Add series name to the label

### ISSUE THREAD

**Issue by Shijie-Shi** [jpazvd/wbopendata#9]
This is such a great initiative! Thank you for creating this package. A minor improvement could be done by adding the series name to the label of each indicator. Right now the label is the same as the indicator name which is Stata's default setting. Though researchers who run the code should have already know what indicators they are getting, adding the explanatory labels seems not necessary in this scenario. However, when sharing the data with other colleagues, having clear labeled variables will be extreme helpful. It is possible that some series name in the current mapping (series code to series name) reach the maximum length of the allowed label length. You may need to come up with another mapping that has short series names. Just an idea.

**Comment by jpazvd** [comment]
Many thanks for your suggestion,

Keep in mind that this feature is currently supported when data is exported in the wide format. 

```
. wbopendata, indicator(ny.gdp.pcap.pp.kd) clear

. list indicatorcode indicatorname in 1

     +-------------------------------------------------------------------------+
     |     indicatorcode                                         indicatorname |
     |-------------------------------------------------------------------------|
  1. | NY.GDP.PCAP.PP.KD   GDP per capita, PPP (constant 2011 international $) |
     +-------------------------------------------------------------------------+
r; t=0.00 7:01:30
```

Regarding the long format, there is a trade-off, between keeping the original variable name or the longer variable description. Our default is to preserve reproducibility, and for that the original variable name is significantly more useful.

However, keep in mind that WBOPENDATA is an R-class command, and the the indicator name is stored in the return list of the command. Hence you can add this information using a single line of code:

```
label var `r(varname1)' "`r(varlabel1)'"
```
Hence, you can add, replace, modify the original variable label before sending the DTA to any collaborator. See example below:

```
. wbopendata, indicator(ny.gdp.pcap.pp.kd) clear long

. return list

macros:
          r(indicator) : "ny.gdp.pcap.pp.kd"
              r(time1) : "year"
          r(varlabel1) : "GDP per capita, PPP (constant 2011 international $)"
            r(source1) : "World Development Indicators"
         r(indicator1) : "ny.gdp.pcap.pp.kd"
           r(varname1) : "ny_gdp_pcap_pp_kd"
r; t=0.00 7:02:24

. label var `r(varname1)' "`r(varlabel1)'"
r; t=0.00 7:10:12

. des

Contains data from C:\Users\wb255520\AppData\Local\Temp\ST_6cc_000001.tmp
  obs:        15,576                          
 vars:            12                          29 Mar 2019 07:02
 size:     2,897,136                          
------------------------------------------------------------------------------------------------
              storage   display    value
variable name   type    format     label      variable label
------------------------------------------------------------------------------------------------
countrycode     str3    %9s                   Country Code
countryname     str52   %52s                  Country Name
region          str3    %9s                   Region Code
regionname      str28   %28s                  Region Name
adminregion     str3    %9s                   Administrative Region Code
adminregionname str52   %52s                  Administrative Region Name
incomelevel     str3    %9s                   Income Level Code
incomelevelname str19   %19s                  Income Level Name
lendingtype     str3    %9s                   Lending Type Code
lendingtypename str14   %14s                  Lending Type Name
year            int     %9.0g                 Year
ny_gdp_pcap_p~d float   %8.0g                 GDP per capita, PPP (constant 2011 international $)
------------------------------------------------------------------------------------------------
Sorted by: countrycode  year
     Note: Dataset has changed since last saved.
r; t=0.00 7:10:16

```

I hope this helps. Many thanks for your questions/suggestion.

Best regards,

JP
